# Site settings
title: Felipe Sere
description: 'My path to craftsmanship.'
url: 'http://felipesere.github.io'
baseurl: '/'

author:
  name: 'Felipe Sere'
  email: felipe@8thlight.com
  twitter_username: felipesere
  github_username:  felipesere

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-twitter-plugin']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'live']
